### ISSUE TITLE
Тестирование API

### ISSUE THREAD

**Issue by WebMad** [WebMad/citron#11]
Тестирование - неотъемлемая часть разработки ПО. На данный момент нам необходимо тестировать API, в этой задаче вы обучитесь тестированию с помощью Postman.

Во-первых скачайте postman: https://www.getpostman.com/

Дальше. Есть несколько типов запросов, приведу те, которые вы будете использовать:
GET
POST
DELETE
PUT
Внимательно читайте документацию, там указан способ отправки данных.
Кстати о документации: https://alecmei-gubin.gitbook.io/citron-system/

Ссылка на актуальную версию сайта: http://chtkorabel.beget.tech/

Ваша задача:

- [x] Попытайтесь зарегистрировать на сайте с помощью postman. Все необходимые для этого методы вы можете найти в документации.
- [x] Попробуйте получить список всех ролей в системе.

**Comment by JeffFreeTVs** [comment]
При попытке получить список всех ролей в системе, выдаёт ошибку 400 bad request
"Authorization Token not found"

**Comment by WebMad** [comment]
Перед тем как получить все роли, необходимо получить токен при авторизации и передавать его параметром "token"
